// DO NOT EDIT THIS FILE MANUALLY,
// GENERATED ACCORDING TO 01-ca_config.txt.

#define STATES 8
#define CA_STEPS 30
#define CA_ROWS 16
#define CA_COLS 16
#define RWIDTH 6
#define RHEIGHT 6
#define REPLICS_REQ 4
