// DO NOT EDIT THIS FILE MANUALLY,
// GENERATED ACCORDING TO 01-ca_config.txt.

#define STATES 8
#define CA_STEPS 30
#define CA_ROWS 9
#define CA_COLS 13
#define RWIDTH 13
#define RHEIGHT 9
#define REPLICS_REQ 4
